[features]
seeds = true
skip-lint = false
[programs.localnet]
pooltowin = "FPpwkb2FsmhYnUXfbrxkE5HpwKZsbCcwExDUudrVdGdY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/denimcodes/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
